version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  transaction-service:
    build:
      context: ./services/transaction_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - neo4j
      - redis
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - REDIS_URI=redis://redis:6379
      - FLASK_APP=app.py
      - FLASK_ENV=development



volumes:
    neo4j_data:
    neo4j_logs:
    redis_data:






